/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseAmountTextField: typeof import('./src/components/Base/BaseAmountTextField.vue')['default']
    BaseAutoComplete: typeof import('./src/components/Base/BaseAutoComplete.vue')['default']
    BaseCardLayout: typeof import('./src/components/Base/BaseCardLayout.vue')['default']
    BaseComboBox: typeof import('./src/components/Base/BaseComboBox.vue')['default']
    BaseFullLayout: typeof import('./src/components/Base/BaseFullLayout.vue')['default']
    BaseIconButton: typeof import('./src/components/Base/BaseIconButton.vue')['default']
    BaseKeyValueSimpleTable: typeof import('./src/components/Base/BaseKeyValueSimpleTable.vue')['default']
    BaseModal: typeof import('./src/components/Base/BaseModal.vue')['default']
    BaseNumberPicker: typeof import('./src/components/Base/BaseNumberPicker.vue')['default']
    BaseSelect: typeof import('./src/components/Base/BaseSelect.vue')['default']
    BaseSqaureButton: typeof import('./src/components/Base/BaseSqaureButton.vue')['default']
    BaseStepper: typeof import('./src/components/Base/BaseStepper.vue')['default']
    BaseStepperLayout: typeof import('./src/components/Base/BaseStepperLayout.vue')['default']
    BaseTabLayout: typeof import('./src/components/Base/BaseTabLayout.vue')['default']
    BaseTable: typeof import('./src/components/Base/BaseTable.vue')['default']
    BaseTextArea: typeof import('./src/components/Base/BaseTextArea.vue')['default']
    BaseTextField: typeof import('./src/components/Base/BaseTextField.vue')['default']
    BaseTimeInputField: typeof import('./src/components/Base/BaseTimeInputField.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    DeleteDialog: typeof import('./src/components/DeleteDialog.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    ReferToAutoComplete: typeof import('./src/components/Base/Custom/ReferToAutoComplete.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
  }
}
